language: ruby
sudo: false
cache:
- apt
- bundler
- npm
git:
  submodules: false
rvm:
- 2.2
env:
- DEBUGBUILD=travis-$TRAVIS_JOB_NUMBER DEBUGBUILD TESTS=ci-cluster-0
- DEBUGBUILD=travis-$TRAVIS_JOB_NUMBER DEBUGBUILD TESTS=ci-cluster-1
- DEBUGBUILD=travis-$TRAVIS_JOB_NUMBER DEBUGBUILD TESTS=ci-cluster-2
- DEBUGBUILD=travis-$TRAVIS_JOB_NUMBER DEBUGBUILD TESTS=ci-cluster-3
script:
- bundle exec rake test[$TESTS]
- bundle exec rake logs2s3
- bundle exec ./.travis.sh publish
before_install:
- npm update
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
xaddons:
  firefox: latest
