---
language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.1.3
env:
- TAG="--tag @test-cluster-0 --tag ~@noci"
- TAG="--tag @test-cluster-1 --tag ~@noci"
- TAG="--tag @test-cluster-2 --tag ~@noci"
- TAG="--tag ~@test-cluster-0 --tag ~@test-cluster-1 --tag ~@test-cluster-2 --tag ~@noci"
script:
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  - bundle exec rake
  - bundle exec cucumber --strict $TAG
before_install:
- npm update
after_success:
  - ./.travis.sh succeeded
after_failure:
  - ./.travis.sh failed
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
