language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.2
env:
- TESTS=383
- TESTS=ci-cluster-0
- TESTS=ci-cluster-1
- TESTS=ci-cluster-2
- TESTS=ci-cluster-3
script:
- echo $PATH
- bundle exec rake test[$TESTS]
- bundle exec rake logs2s3
- bundle exec ./.travis.sh publish
before_install:
- npm update
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
addons:
  firefox: latest
