---
language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.1.3
env:
- TAG="--tag @test-cluster-0 --tag ~@noci"
- TAG="--tag @test-cluster-1 --tag ~@noci"
- TAG="--tag @test-cluster-2 --tag ~@noci"
- TAG="--tag ~@test-cluster-0 --tag ~@test-cluster-1 --tag ~@test-cluster-2 --tag ~@noci"
script:
  - bundle exec rake
  - bundle exec cucumber --strict $TAG
before_install:
- npm update
- dpkg -l | grep firefox
