---
language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.1.3
env:
- TAG=import
- TAG=export1
- TAG=export2
- TAG=bulkexport
script: bundle exec rake test[$TAG]
before_install:
- npm update
ignore_before_install:
- sudo apt-get update
- sudo apt-get install nodejs npm firefox
