language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.2
env:
- TAG="--tag @test-cluster-0 --tag ~@noci"
- TAG="--tag @test-cluster-1 --tag ~@noci"
- TAG="--tag @test-cluster-2 --tag ~@noci"
- TAG="--tag ~@test-cluster-0 --tag ~@test-cluster-1 --tag ~@test-cluster-2 --tag ~@noci"
script:
- bundle exec rake
- bundle exec cucumber --strict $TAG
- bundle exec ./.travis.sh publish
before_install:
- npm update
notifications:
  slack:
    secure: FrH2x+zMD/961jEEzvtwxdq8eKTddPDT98cFig7vFxKNrW6rs6ogPl9Mbq9KpxVq/a4Q7dmbri0JKn7hv94pch1fCBIOqeqrgbelbn3/MrhAHDIUU1jJCDDbvs2W5H8bEWgBwmZVEMjg/6yHwBKXFOUGwV3CAO1GMKhknQbCTi8=
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
