---
language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.1.3
env:
- TAG=--tag @test-cluster-0 --tag ~@noci
- TAG=--tag @test-cluster-1 --tag ~@noci
- TAG=--tag @test-cluster-2 --tag ~@noci
- TAG=--tag ~@test-cluster-0 --tag ~@test-cluster-1 --tag ~@test-cluster-2 --tag ~@noci
script: bundle exec cucumber $TAG
before_install:
- npm update
ignore_before_install:
- sudo apt-get update
- sudo apt-get install nodejs npm firefox
