language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.2
env:
- CLUSTER=0
- CLUSTER=1
- CLUSTER=2
- CLUSTER=3
script:
- echo $PATH
- bundle exec rake test[ci-cluster-$CLUSTER]
- bundle exec ./.travis.sh publish
before_install:
- npm update
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
