language: ruby
sudo: false
cache:
- apt
- bundler
rvm:
- 2.2
env:
- TAG="--tag @test-cluster-0 --tag ~@noci"
- TAG="--tag @test-cluster-1 --tag ~@noci"
- TAG="--tag @test-cluster-2 --tag ~@noci"
- TAG="--tag ~@test-cluster-0 --tag ~@test-cluster-1 --tag ~@test-cluster-2 --tag ~@noci"
script:
- echo $PATH
- bundle exec rake test[none]
- bundle exec cucumber --require features --strict $TAG resource/tests
- bundle exec ./.travis.sh publish
before_install:
- npm update
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
